# Generated by Django 2.2.8 on 2019-12-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huifu',
            fields=[
                ('huifu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiezi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sch_id', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('dianzan_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Huifu',
            },
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('sch_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ID',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_name', models.CharField(default='user_photo', max_length=250, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='user_photo.jpg', height_field='url_height', upload_to='image', width_field='url_width')),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='BBSServer.Id')),
                ('username', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('grade', models.CharField(blank=True, max_length=4, null=True)),
                ('academy', models.CharField(blank=True, max_length=255, null=True)),
                ('fatie_num', models.IntegerField()),
                ('guanzhu_num', models.IntegerField()),
                ('shouchang_num', models.IntegerField()),
                ('fensi_num', models.IntegerField()),
                ('register_date', models.DateField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Shoucang',
            fields=[
                ('sch_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tiezi_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Shoucang',
                'unique_together': {('sch_id', 'tiezi_id')},
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pic_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tiezi_id', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Picture',
                'unique_together': {('pic_id', 'tiezi_id')},
            },
        ),
        migrations.CreateModel(
            name='Guanzhu',
            fields=[
                ('sch_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('b_sch_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Guanzhu',
                'unique_together': {('sch_id', 'b_sch_id')},
            },
        ),
        migrations.CreateModel(
            name='Dianzan',
            fields=[
                ('tiezi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sch_id', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Dianzan',
                'unique_together': {('tiezi_id', 'sch_id', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Tiezi',
            fields=[
                ('tiezi_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('dianzan_num', models.IntegerField(blank=True, null=True)),
                ('liulan_num', models.BigIntegerField(blank=True, null=True)),
                ('sch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='BBSServer.Id')),
            ],
            options={
                'db_table': 'Tiezi',
                'unique_together': {('tiezi_id', 'sch')},
            },
        ),
    ]
